### ISSUE TITLE
AORT

### ISSUE THREAD

**Issue by AyoubNajim** [gwen001/offsectools_www#281] opened 2022-12-26 10:55 UTC

**Comment by AyoubNajim** [comment] 2022-12-26 11:02
Description : 
An easy-to-use python tool to perform dns recon, subdomain enumeration and much more
The purpouse of this tool is helping bug hunters and pentesters during reconnaissance.

Link : https://github.com/AyoubNajim/AORT

Tags : #subdomains #dns #ips #scanner

![image](https://user-images.githubusercontent.com/68334573/209541613-d95faf08-ddfb-4fff-9b4d-faf1a844017b.png)

**Comment by gwen001** [comment] 2022-12-26 11:57
Sorry but the bot cannot handle this issue because it doesn't respect the required format.

Please edit the original issue according the guidelines here https://github.com/gwen001/offsectools_www/issues/1

Thank you for your understanding.

**Comment by gwen001** [comment] 2023-02-08 09:32
Duplicate of https://github.com/gwen001/offsectools_www/issues/781

**Closed by gwen001** 2023-02-08 09:32 UTC
