### ISSUE TITLE
[addtool] TLDHunt

### ISSUE THREAD

**Issue by yuyudhn** [gwen001/offsectools_www#1302] opened 2023-06-04 12:05 UTC
[link]https://github.com/yuyudhn/TLDHunt[/link]
[tags]shell, whois, redteaming[/tags]
[short_descr]Domain Availability Checker[/short_descr]
[long_descr]TLDHunt is a command-line tool designed to help users find available domain names for their online projects or businesses. By providing a keyword and a list of TLD (top-level domain) extensions, TLDHunt checks the availability of domain names that match the given criteria. This tool is particularly useful for those who want to quickly find a domain name that is not already taken, without having to perform a manual search on a domain registrar website.
For red teaming or phishing purposes, this tool can help you to find similar domains with different extensions from the original domain.[/long_descr] 
[image]
https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg1mrljuonzhjuuPoc9Bn_rH1X-drfrPHm1fYew52STZw7sHf8Pa6oQflj1ZOcm9FQKw7wVlRPn6gZDQoKFpnzXEe6bjcQ6dF8cMnKIkhbSHx4Mt9Qz24NaXgfTifapzuO3_8qP-1c53N0jLdotvi9bmbfIx8VyjP_ukDv_bu49kxLOBPFSlgRXXRfgAg/s782/tldhunt.png
[/image]

**Comment by gwen001** [comment] 2023-06-04 12:07
Duplicate of https://github.com/gwen001/offsectools_www/issues/1302

**Closed by gwen001** 2023-06-04 12:07 UTC
Labels: duplicate

**Comment by yuyudhn** [comment] 2023-06-04 13:06
how this can be duplicate to same issue...

**Comment by gwen001** [comment] 2023-06-05 14:41
Tool has been accepted by the team: https://offsec.tools/tool/domains,tld,recon

Thank you for your contribution!
