### ISSUE TITLE
[addtool] MSOLSpray

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1123] opened 2023-05-04 06:02 UTC
[homepage] https://github.com/dafthack/MSOLSpray [/homepage]
[tags] all,password,spraying,microsoft [/tags]
[short_descr] A password spraying tool for Microsoft Online accounts (Azure/O365). [/short_descr]
[long_descr] A password spraying tool for Microsoft Online accounts (Azure/O365). The script logs if a user cred is valid, if MFA is enabled on the account, if a tenant doesn't exist, if a user doesn't exist, if the account is locked, or if the account is disabled. [/long_descr] 
[image] 
![image](https://user-images.githubusercontent.com/5957301/236123330-d6f2f51b-a436-4f12-b040-958af163b7e8.png)
 [/image]

**Comment by gwen001** [comment] 2023-05-04 12:36
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment] 2023-05-04 13:57
Duplicate of https://github.com/gwen001/offsectools_www/issues/1123

**Comment by gwen001** [comment] 2023-05-04 13:58
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment] 2023-05-04 14:00
Duplicate of https://github.com/gwen001/offsectools_www/issues/1123

**Comment by gwen001** [comment] 2023-05-04 14:01
Duplicate of https://github.com/gwen001/offsectools_www/issues/1123

**Comment by gwen001** [comment] 2023-05-04 14:01
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment] 2023-05-04 16:18
Tool has been accepted by the team: https://offsec.tools/tool/msolspray

Thank you for your contribution!

**Comment by gwen001** [comment] 2023-05-04 16:19
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment] 2023-05-04 16:19
Tool has been accepted by the team: https://offsec.tools/tool/msolspray

Thank you for your contribution!

**Comment by gwen001** [comment] 2023-05-04 16:19
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Closed** 2023-05-04 16:20 UTC
Labels: enhancement
