### ISSUE TITLE
[addtool] Airi

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1173] opened 2023-05-10 06:47 UTC
[link] https://github.com/ferreiraklet/Airi [/link]
[tags] all,hidden,input,scanner,html [/tags]
[short_descr] Airi is made to find hidden input parameters in web applications. [/short_descr]
[image] https://github-production-user-asset-6210df.s3.amazonaws.com/5957301/237301405-c24a36a5-5aa4-4df8-a336-9d3a6bcc371e.png [/image]

**Comment by gwen001** [comment] 2023-05-10 06:48
Duplicate of https://github.com/gwen001/offsectools_www/issues/1171

**Closed by gwen001** 2023-05-10 06:48 UTC
Labels: duplicate

**Comment by euriconicacio** [comment] 2023-05-10 06:49
@gwen001, this is not a duplicate. 😃
