### ISSUE TITLE
[addtool] Airi

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1171] opened 2023-05-10 06:42 UTC
[link] https://github.com/ferreiraklet/Airi [/link]
[tags] all,hidden,input,scanner,html [/tags]
[short_descr] Airi is made to find hidden input parameters in web applications. [/short_descr]
[image] https://camo.githubusercontent.com/9d050b323305a025ac2e03500ae56c0dfc1f026e1d8fd3d17fbcb199a505a75b/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3837363931393534303638323938393630392f3934343633393331363439343237343636302f756e6b6e6f776e2e706e67 [/image]

**Comment by gwen001** [comment] 2023-05-10 06:44
Duplicate of https://github.com/gwen001/offsectools_www/issues/1171

**Closed by gwen001** 2023-05-10 06:44 UTC

**Comment by gwen001** [comment] 2023-05-17 15:08
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
