### ISSUE TITLE
[addtool] shells2

### ISSUE THREAD

**Issue by 4ndr34z** [gwen001/offsectools_www#1450] opened 2023-10-12 19:02 UTC
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]https://github.com/4ndr34z/shells[/link]

[tags]shell, shells,shellz,powershell,ruby,bash,netcat,generator,revshell,reverse-shell[/tags]
[short_descr]A script for generating common revshells fast and easy.
Especially nice when in need of PowerShell and Python revshells, which can be a PITA getting correctly formatted.[/short_descr]

[long_descr]
Shows username@computer.(domain), above the prompt and working-directory
Has a partial and full AMSI-bypass.
TCP, UDP and SSL shells
New custom TCP revshell!
New custom SSL revshell!
Reflective loading [theart42's](https://twitter.com/theart42) amazing Sharpcat!
Windows Powershell and Core Powershell
Functions for uploading and downloading files. (Using [Updog](https://github.com/sc0tfree/updog) by sc0tfree)
[/long_descr]
[image]https://github.com/4ndr34z/shells/blob/main/screenshots/macOS162.png?raw=true[/image]

**Comment by gwen001** [comment] 2023-10-12 19:03
Problem occured with the following fields:
- `short_descr` not found
- `tags` not found
- `link` not found
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment] 2023-12-17 11:26
Duplicate of https://github.com/gwen001/offsectools_www/issues/531

**Comment by gwen001** [comment] 2023-12-17 11:56
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment] 2023-12-17 11:57
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment] 2024-05-07 15:33
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Closed by gwen001** 2024-05-07 15:33 UTC
Labels: enhancement, refused
