### ISSUE TITLE
[addtool] Tool NiceName

### ISSUE THREAD

**Issue by ggjey** [gwen001/offsectools_www#1654] opened 2024-03-12 18:04 UTC
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

Put your data between the `[opening-tags]` and the `[/closing-tags]`.

Link to the tool: https://... (minimum 1 required):
[link]https://www.saas-sentinel.gitguardian.com/[/link]
[link][/link]
[link][/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags]honeytoken, credentials, backend, bitbucket, github, gitlab, confluence, passwords, secrets, scm[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Get notified if a honeytoken is triggered on one of your favorite dev tool. [/short_descr]

A bigger description (optional, but nice to have):
[long_descr]SaaS Sentinel is looking to help organizations detect intrusion as it unfolds and reduce the Mean-Time-to-Detect.

While in an ideal world, our perimeter defenses would be unbreachable, the reality is attackers are persistent and always finding new ways around the barriers we put up. However, once they are in, almost all attackers behave fairly predictably, and we can use this and a little cyber deception to our advantage to trick them into revealing themselves.
[/long_descr]

A link or an attached image (minimum 1 required):
[image]https://uploads-ssl.webflow.com/63ebbbaf4944fd864db37a7e/63ec3821e7fe50af3d8b0702_banner-image.svg[/image]
[image]https://uploads-ssl.webflow.com/63ebbbaf4944fd864db37a7e/63f2ab13cdf34e6407b7ade7_Logo.svg[/image]
[image]https://blog.gitguardian.com/content/images/size/w2000/2023/04/23W17-blog-HowWeBuiltaSupplyChainSecurityWatchtower_-MeetSaaS-Sentinel.png[/image]
[image]https://blog.gitguardian.com/content/images/2023/04/data-src-image-25875590-86d8-4489-b1c0-4e05884b1a05.png[/image]
[image]https://blog.gitguardian.com/content/images/2023/04/23W17-blog-content-saas-sentinel-1.png[/image]

**Comment by gwen001** [comment] 2024-03-12 18:05
Duplicate of https://github.com/gwen001/offsectools_www/issues/1136

**Closed by gwen001** 2024-03-12 18:05 UTC
Labels: duplicate, enhancement
