### ISSUE TITLE
Wifipass

### ISSUE THREAD

**Issue by bhanugoudm041** [gwen001/offsectools_www#715] opened 2023-01-25 09:07 UTC
[link]https://github.com/bhanugoudm041/wifipass[link]
[short_descr]A simple Wireless Networks Penetration Testing Toolkit[short_descr]
[long_descr]WifiPass is a small wireless networks penetration testing toolkit. It has many feature such as enabling monitor mode, 
 disabling monitor mode, caputuring handshakes & also it can crack the wireless networks passwords. It also has a speacial feature that will rename the network interfaces.[long_descr]

**Comment by gwen001** [comment] 2023-01-25 12:00
Sorry but the bot cannot handle this issue because it doesn't respect the required format.

Please edit the original issue according the [guidelines](https://github.com/gwen001/offsectools_www/issues/1), or use the issue template created for that purpose to avoid any mistake.
You can also check one of the issue already closed to see how it's supposed to be.

Thank you for your understanding.

**Comment by gwen001** [comment] 2023-01-25 21:29
Duplicate of https://github.com/gwen001/offsectools_www/issues/717

**Closed** 2023-01-25 21:29 UTC
