### ISSUE TITLE
[addtool] gitlab-subdomains

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#109] opened 2022-12-13 10:56 UTC
[link]https://github.com/gwen001/gitlab-subdomains[/link]
[short_descr] Find subdomains on GitLab. [/short_descr]
[tags]gitlab,subdomain,recon[/tags]
[long_descr] Find subdomains on GitLab. [/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207299539-b574b055-5e58-4969-be88-2d4174755cf9.png)

**Comment by gwen001** [comment] 2022-12-13 10:57
Duplicate of https://github.com/gwen001/offsectools_www/issues/37

**Closed by gwen001** 2022-12-13 10:57 UTC
Labels: duplicate
