### ISSUE TITLE
[addtool] JWT Tool

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#624] opened 2023-01-16 09:28 UTC
[homepage] https://github.com/ticarpi/jwt_tool [/homepage]
[tags] all,web,token,jwt (required)[/tags]
[short_descr] JWT Tool is a toolkit for validating, forging, scanning, and tampering JWTs. [/short_descr]
[long_descr] This tool is written for pentesters, who need to check the strength of the tokens in use, and their susceptibility to known attacks. A range of tampering, signing, and verifying options are available to help delve deeper into the potential weaknesses present in some JWT libraries. [/long_descr] 
[image] https://user-images.githubusercontent.com/19988419/100555535-18598280-3294-11eb-80ed-ca5a0c3455d6.png [/image]

**Comment by gwen001** [comment] 2023-01-16 09:29
Duplicate of https://github.com/gwen001/offsectools_www/issues/101

**Closed by gwen001** 2023-01-16 09:29 UTC
Labels: duplicate
